(part "MCS0630-100MN1"
    (packageRef "INDPM7366X300N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "Prosperity Dielectrics")
    (property "Manufacturer_Part_Number" "MCS0630-100MN1")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Inductors (SMD) 0630,SMD,7.3x6.6mm RoHS")
    (property "Datasheet_Link" "https://datasheet.lcsc.com/szlcsc/1904111132_Prosperity-Dielectrics-MCS0630-100MN1_C385254.pdf")
    (property "symbolName1" "MCS0630-100MN1")
)
