(part "SS-12D10L3"
    (packageRef "SS12D10L3")
    (interface
        (port "1" (symbPinId 1) (portName "NC") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NO") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "XKB Connectivity")
    (property "Manufacturer_Part_Number" "SS-12D10L3")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Toggle switch, vertical foot two gears, plug, single row high temperature salt fog resistant 24 hours,13x6.8x6.4 flat black handle 3mm")
    (property "Datasheet_Link" "http://www.helloxkb.com/public/images/pdf/SS-12D10XXX.pdf")
    (property "symbolName1" "SS-12D10L3")
)
