(part "PTS647SM50SMTR2LFS"
    (packageRef "PTS647SM50SMTR2LFS")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "C & K COMPONENTS")
    (property "Manufacturer_Part_Number" "PTS647SM50SMTR2LFS")
    (property "Mouser_Part_Number" "611-PTS647SM50SMTR2L")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/CK/PTS647SM50SMTR2LFS?qs=PqoDHHvF64%252BjK4ZB7f42kw%3D%3D")
    (property "Arrow_Part_Number" "PTS647SM50SMTR2LFS")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/pts-647-sm50-smtr2-lfs/ck?region=europe")
    (property "Description" "Tactile Switches 50mA 12VDC, 1.8N 5.0mm H, G leads")
    (property "Datasheet_Link" "https://www.ckswitches.com/media/2567/pts647.pdf")
    (property "symbolName1" "PTS647SM50SMTR2LFS")
)
